---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-cloud-tagger
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-cloud-tagger
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cloud-tagger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-cloud-tagger
subjects:
  - kind: ServiceAccount
    name: k8s-cloud-tagger
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cloud-tagger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-cloud-tagger
  template:
    metadata:
      labels:
        app: k8s-cloud-tagger
    spec:
      serviceAccountName: k8s-cloud-tagger
      containers:
      - name: controller
        image: image
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
