{{- if and (eq .Values.cloudProvider "azure") (.Values.azure.serviceOperator.enabled) }}
apiVersion: managedidentity.azure.com/v1api20230131
kind: FederatedIdentityCredential
metadata:
  name: {{ include "k8s-cloud-tagger.fullname" . }}-wi-binding
spec:
  owner:
    name: {{ include "k8s-cloud-tagger.azure.managedIdentity" . }}
  audiences:
    - api://AzureADTokenExchange
  issuer: {{ required "azure.serviceOperator.oidcIssuerUrl is required" .Values.azure.serviceOperator.oidcIssuerUrl }}
  subject: system:serviceaccount:{{ .Release.Namespace }}:{{ include "k8s-cloud-tagger.fullname" . }}
{{- end }}
