{{- if and (eq .Values.cloudProvider "azure") (.Values.azure.serviceOperator.enabled) }}
apiVersion: managedidentity.azure.com/v1api20230131
kind: UserAssignedIdentity
metadata:
  name: {{ include "k8s-cloud-tagger.azure.managedIdentity" . }}
spec:
  location: {{ required "azure.location is required" .Values.azure.location }}
  owner:
    name: {{ required "azure.resourceGroup is required" .Values.azure.resourceGroup }}
  operatorSpec:
    configMaps:
      principalId:
        name: {{ include "k8s-cloud-tagger.azure.identityConfigMap" . }}
        key: principalId
{{- end }}
