{{- if and (eq .Values.cloudProvider "azure") (.Values.azure.serviceOperator.enabled) }}
apiVersion: authorization.azure.com/v1api20220401
kind: RoleDefinition
metadata:
  name: {{ include "k8s-cloud-tagger.fullname" . }}
spec:
  owner:
    name: {{ required "azure.subscriptionId is required" .Values.azure.subscriptionId }}
    group: resources.azure.com
    kind: Subscription
  roleName: {{ .Values.azure.serviceOperator.customRoleName }}
  description: Read and set tags on managed disks
  type: CustomRole
  permissions:
    - actions:
        - Microsoft.Compute/disks/read
        - Microsoft.Compute/disks/write
{{- end }}
