{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-cloud-tagger.fullname" . }}
  labels:
    {{- include "k8s-cloud-tagger.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- if eq .Values.cloudProvider "azure" }}
    azure.workload.identity/use: "true"
    {{- end }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.serviceAccount.annotations (eq .Values.cloudProvider "gcp") (eq .Values.cloudProvider "azure") (and (eq .Values.cloudProvider "aws") .Values.aws.controllersKubernetes.enabled) }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.cloudProvider "gcp" }}
    iam.gke.io/gcp-service-account: {{ .Values.gcp.serviceAccount }}@{{ .Values.gcp.projectId }}.iam.gserviceaccount.com
    {{- end }}
    {{- if eq .Values.cloudProvider "azure" }}
    azure.workload.identity/client-id: {{ required "azure.clientId is required when cloudProvider=azure" .Values.azure.clientId }}
    {{- end }}
    {{- if and (eq .Values.cloudProvider "aws") .Values.aws.controllersKubernetes.enabled }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ required "aws.controllersKubernetes.accountId is required when cloudProvider=aws and controllersKubernetes.enabled" .Values.aws.controllersKubernetes.accountId }}:role/{{ .Values.aws.controllersKubernetes.roleName }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
